name: Deploy to Netlify

on:
  push:
    branches:
      - main
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Create .env.production file
        run: |
          echo "VITE_API_BASE_URL=/api" > .env.production
          echo "VITE_USE_MOCK_API=true" >> .env.production
          echo "VITE_APP_ENV=production" >> .env.production
      
      - name: Build client
        run: npm run client:build
      
      - name: Create Netlify redirects file
        run: |
          echo "/* /index.html 200" > dist/public/_redirects
      
      - name: Deploy to Netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          args: deploy --dir=dist/public --prod
